name: Rust checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SetupRust
      uses: ATiltedTree/setup-rust@v1
      with:
        # FIXME: We want "stable" here, but 1.71 isn't working
        # DATE: 2023-07-14
        rust-version: "1.70"
    - name: cargo fmt
      run: |
        # Hack: setup-rust seems to fail to install this?
        rustup component add rustfmt
        cd fish-rust
        cargo fmt --check --all

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SetupRust
      uses: ATiltedTree/setup-rust@v1
      with:
        # FIXME: We want "stable" here, but 1.71 isn't working
        # DATE: 2023-07-14
        rust-version: "1.70"
    - name: Install deps
      run: |
        sudo apt install gettext libncurses5-dev libpcre2-dev python3-pip tmux
        sudo pip3 install pexpect
    - name: cmake
      run: |
        cmake -B build
    - name: cargo clippy
      run: |
        # Hack: setup-rust seems to fail to install this?
        rustup component add clippy
        cd fish-rust
        cargo clippy --workspace --all-targets -- --deny=warnings
